### ISSUE TITLE
Distinguish 3 GiB and 2 GiB PinePhone models at runtime

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode-allwinner#18]
Currently, the kernel is hard-wired to the 3 GiB version by the `RAM_SIZE` definition in https://github.com/genodelabs/genode-allwinner/blob/master/src/include/hw/spec/arm_64/pine_a64lts_board.h, which is taken as input for the physical memory allocator of core/kernel https://github.com/genodelabs/genode-allwinner/blob/master/src/bootstrap/board/pine_a64lts/platform.cc.

Since both PinePhone variants are used in practice, we should better replace this hard-coded value by a value detected at runtime.

**Comment by ssumpf** [comment]
@nfeske: 5d26e89 has been tested on 2 and 3 GB models.

**Comment by nfeske** [comment]
Very cool! Just in time for the Sculpt release. :-) I just gave it a successful try on my PinePhone.
