### ISSUE TITLE
Lower MMC0 clock

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode-allwinner#19]
As reported on the [Pine64 forum]( https://forum.pine64.org/showthread.php?tid=14780&pid=117311#pid117311) running the MMC0 controller (the one the SD card is attached to) at _150_ MHz poses a problem depending on the used card. So revert back to the initial setting of _100_ MHz.

**Comment by cnuke** [comment]
Commit [b789c8](https://github.com/cnuke/genode-allwinner/commit/b789c815131aa0bf6d9d75a088bb4af10bec607d) addresses the issue.

**Comment by nfeske** [comment]
Thank you. Merged to staging.
