### ISSUE TITLE
a64_linux: mirror is no longer updated and will be removed soon

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode-allwinner#24]
The mirror https://github.com/megous/linux/ is no longer maintained and `./tool/ports/prepare_port a64_linux` fails because of missing source archive.

@cnuke any ideas?

**Comment by cnuke** [comment]
@chelmuth these short-term solution would be to host the archive ourselves and long-term how to efficently work woth the bundles; I'll look into that.

**Comment by cnuke** [comment]
@chelmuth commit [7194ed7](https://github.com/cnuke/genode-allwinner/commit/7194ed732df47e7e6a56b467427a3c0fc661639f) addresses the issue short-term.

**Comment by chelmuth** [comment]
Thanks, merged to staging.

**Comment by chelmuth** [comment]
Fixed for now.
