### ISSUE TITLE
uboot.env: reset system on failed loading step

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode-allwinner#26]
When creating the SD-card image we also generate a _uboot.env_ file that amongst others stores the `bootcmd` variable. There we instruct U-Boot to first load our _uImage_ and then to boot it via `bootm`. It sometimes happens that the file cannot be read (normally marked with an 'fs_devread' error message) or that the file was read incorrectly (_Bad Data CRC_) despite the file being correctly stored on the SD-card. To remedy the effect we now reset the system after each failed step in the hope that those errors are only temporary in nature.

**Comment by cnuke** [comment]
Commit [9bf1f5f](https://github.com/cnuke/genode/commit/9bf1f5f25f8d66b773cd01b992e24224012e4d31) extends the `sculpt_image.run` run-script to also copy the _uboot.env_ file (I added the `cp` operation directly to the block _cping_ the image file - that could be generalized if we need to have similar treatment on other platforms) and commit [26b8e36](https://github.com/cnuke/genode-allwinner/commit/26b8e36c507e0b0e2fbab082ef6cc603fbe14289) adds the `reset` calls to the command.

**Comment by nfeske** [comment]
Thank you @cnuke. I merged both commits to the respective staging branches.
