### ISSUE TITLE
gpu/lima: remove handling of I/O signals

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode-allwinner#27]
With the introduce of the context-handling and the accompanying changes the driver now longer has to depend on the occurrence of I/O signals and their explicit handling via `wait_and_dispatch_io_signal` can be removed.

**Comment by cnuke** [comment]
Commit [660e178](https://github.com/cnuke/genode-allwinner/commit/660e1780c511bac618cd49d907023f5c91e6eaa3) contains a _WIP_ implementation that works in practice but I have not checked every corner-case yet.

**Comment by cnuke** [comment]
Further testing revealed no short-comings so commit [68d0c12](https://github.com/cnuke/genode-allwinner/commit/68d0c12d431256d6582c5bd70bc69b442fbe13e6) is good to go.

During testing I also notice a bug in the `libdrn/lima` that commit [924227a](https://github.com/cnuke/genode/commit/924227afb4dc2783ba87fcd8bcc421f7d009bf8f) addresses. That being said, Mesa does not anticipate allocations to fail (that goes for some other ioctls as well) and the client will fault anyway.

**Comment by nfeske** [comment]
Thank you. I merged both commits to the respective staging branches.

**Comment by nfeske** [comment]
Fixed in master.
