### ISSUE TITLE
Add SD/MMC driver

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode-allwinner#6]

**Comment by cnuke** [comment]
The following commits provide the `a64_sd_card_drv`:

* 1340d6b - a64_linux: enable MMC/SD card driver
* f48245d - initcall_order: add MMC/SD initcalls
* 1e61a13 - a64_platform_drv: add MMC settings
* d31da07 - sd_card/a64: add driver for SD/MMC

**Comment by nfeske** [comment]
Thanks a lot for the excellent commit series, which I promptly merged to staging. I'm looking forward to give this driver a spin.
