### ISSUE TITLE
SIM PIN entry may not work when entering the PIN too quickly

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode-allwinner#9]
@cproc and @jschlatow reported problems with entering the SIM PIN. By analyzing the respective AT-protocol traces, one could spot a bad interplay between the `AT+QCFG="usbnet"` and `AT+CPIN=xxxx` commands. The erratic behavior of the former (while the modem is booting) leads to the silent dropping of the latter.

**Comment by nfeske** [comment]
@cproc and @jschlatow could you please give https://github.com/genodelabs/genode-allwinner/commit/dddd6af74bc7f09e2658547015e0039d18552053 a try?

**Comment by jschlatow** [comment]
@nfeske Unfortunately, the issue persists. I sent you the log via email.
